### ISSUE TITLE
First sync stuсk at 1st step

### ISSUE THREAD

**Issue by imperiumbee** [men232/plus-for-trello#11]
Hello!
Recently the extension froze, I reset the synchronization and after that the synchronization froze at the first stage.
I tried all versions of the extensions, the result is the same, in the screenshots below.

(On Windows and Mac the result is the same)

<img width="241" alt="Снимок экрана 2024-09-07 в 12 18 47" src="https://github.com/user-attachments/assets/78d773d8-d26a-4040-acbc-1118f2f602d0">
<img width="1361" alt="Снимок экрана 2024-09-07 в 12 22 06" src="https://github.com/user-attachments/assets/dcd600c1-c7a6-4ce8-9f85-b397a9aab82f">

What can I do to fix this?
Maybe I need to give some more info?

Can you help me?

**Comment by men232** [comment]
Hello, I see a problem with capturing the access token. It might be due to the fact that you are logged under organization (cloud auth).

May i ask you to install ext from dev branch, then you will able to see this log message with cookies values
```
handleQueryTrelloToken() - not able to read the token cookies! [...]
```

Please share this, but first make sure you remove the token values before you post it

**Comment by imperiumbee** [comment]
Sorry, i made it with screenshots, copy was very poor style.
<img width="733" alt="Снимок экрана 2024-09-08 в 17 57 11" src="https://github.com/user-attachments/assets/9e44b7f8-0cdd-4e7c-bb88-50c22018b62b">
<img width="435" alt="Снимок экрана 2024-09-08 в 17 57 23" src="https://github.com/user-attachments/assets/358470a3-137e-41c3-9994-b2051ba57b46">
<img width="372" alt="Снимок экрана 2024-09-08 в 17 57 29" src="https://github.com/user-attachments/assets/e8c7962f-c9ed-4bef-9673-242ddbd8cd2f">

**Comment by men232** [comment]
Can you try updated version from dev branch? I added attempt to use a cloud session token which may help

**Comment by imperiumbee** [comment]
Thats great man! It works! THank you very much!
