### ISSUE TITLE
Trello authentication error

### ISSUE THREAD

**Issue by alc-ops** [men232/plus-for-trello#12]
Hello guys!

First of all, thanks for you work with plus for trello!

I upgraded my pft version to 6.5.9 yesterday but it doesn't sync my hours. This is what appears when i hover the mouse:

![pft-err](https://github.com/user-attachments/assets/654c43db-8104-46de-a808-acfaa5983d58)

You know what could it be?

**Comment by men232** [comment]
Hi, can you please check the extension logs for errors or warnings?

**Comment by alc-ops** [comment]
It´s empty :/

![image](https://github.com/user-attachments/assets/df5c24ad-bf41-42f9-b571-8076d0a8541c)

**Comment by men232** [comment]
Ok, can you please try version from dev branch? Please, let me know about result

**Comment by alc-ops** [comment]
It's working now, even so you want me to test the dev branch?
