### ISSUE TITLE
More info about my latest comment in https://trello.com/c/UGi2MhDP/194-extension-is-no-longer-in-the-chrome-store

### ISSUE THREAD

**Issue by AgustinLorenzo** [men232/plus-for-trello#4]
Hi @men232 

Link: https://trello.com/c/UGi2MhDP/194-extension-is-no-longer-in-the-chrome-store

I open the issue so I can give you more information about the last thing I said.

- The report now seems to work correctly.

But with this latest version (6.5.4) the summary of the hours reported by users is not shown

Wrong:

![imagen](https://github.com/men232/plus-for-trello/assets/37807236/78367067-f484-464e-ac6e-84c4b77a736d)

OK: 

![imagen](https://github.com/men232/plus-for-trello/assets/37807236/c0a2f55d-e054-4826-a04c-bd95b0616580)

If you need me to try something tell me, thanks for the support.

Regards, Agustin

**Comment by men232** [comment]
@AgustinLorenzo can you check? :)

**Comment by men232** [comment]
@danielcebrian can you check? :)

**Comment by cangming** [comment]
The problem seems caused by the check of g_optEnterSEByComment.rgKeywords.length.
I have issue a  #5 
Could you check?
Thank you.

**Comment by danielcebrian** [comment]
Thanky you @cangming, I could not reproduce the issue

**Comment by cangming** [comment]
I encounter this problem by specific only one keyword.

**Comment by AgustinLorenzo** [comment]
Hi @cangming 

Fixed, with your change :)

Thanks.

**Comment by men232** [comment]
Fined in v6.5.5
Thanks @danielcebrian @cangming
