### ISSUE TITLE
Icon on board header disappear

### ISSUE THREAD

**Issue by cangming** [men232/plus-for-trello#7]
The board header now:
![image](https://github.com/men232/plus-for-trello/assets/4612664/ad9041be-a347-4c58-8e57-88fc52608298)

Expected:
![image](https://github.com/men232/plus-for-trello/assets/4612664/35a95634-0455-4479-b771-55e3053717fd)

Since trello change the layout of boards. The css selector fail to select the board header. This make icon on board header disappear.
I issue a pull request #6 about it.

**Comment by AgustinLorenzo** [comment]
Hi @cangming 

@men232 okay, this fix work well, you can push to master.

Regards, Agustin
