### ISSUE TITLE
Double icon of plus for trello in comments

### ISSUE THREAD

**Issue by AgustinLorenzo** [men232/plus-for-trello#8]
Hi boys,

Sometimes the plus for trello icon appears in duplicate, has happened to you @cangming?

ping @men232 

![1](https://github.com/men232/plus-for-trello/assets/37807236/0a1e83ee-c2a4-4046-9991-c6a4011cb12b)

![2](https://github.com/men232/plus-for-trello/assets/37807236/f5677f8b-568b-44bc-80c3-2a9145aa8eb7)

Regards, Agustin

**Comment by men232** [comment]
can't reproduce

**Comment by cangming** [comment]
Not happened to me. I'll try to figure out if it happen.
