### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by cangming** [men232/plus-for-trello#9]
Since trello starting to support dark mode, CSS of the plus for trello not sync with trello UI. This make the UI looks strange.
![image](https://github.com/men232/plus-for-trello/assets/4612664/ecf80224-8ef0-4446-a7ce-f5026c73540a)
![image](https://github.com/men232/plus-for-trello/assets/4612664/8535b714-9f7e-44d4-b2b8-5b3c745c7706)
Trello provides css data, it may be a possible solution.
```
html[data-color-mode="light"][data-theme~="light:dark"], html[data-color-mode="dark"][data-theme~="dark:dark"]
```

**Comment by cangming** [comment]
I issue a PR #10 about this issue. @men232 Could you check it? Thank you very mush.

**Comment by men232** [comment]
@cangming
Seems all perfect, thanks :)
